brew "awscli"
brew "bat"
brew "ffmpeg"
brew "ImageMagick"
brew "kubectx"
brew "kubernetes-cli"
brew "nvm"
brew "tmux"
brew "ngrok"
brew "lazygit"
brew "hyperfine"
brew "git-standup"

cask "brave-browser"
cask "cron"
cask "docker"
cask "karabiner-elements"
cask "mongodb-compass"
cask "pgadmin4"
cask "raycast"
cask "spotify"
cask "trailer"

brew "jq"
brew "derailed/k9s/k9s"
tap "hashicorp/tap"
brew "hashicorp/tap/terraform"
brew "hashicorp/tap/terraform-ls"
brew "pnpm"

tap "out-of-cheese-error/the-way"
brew "the-way"
