[[language]]
name = "html"
# Pretier
# formatter = { command = 'prettier', args = ["--parser", "html"] }
# Deno
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "html" ] }

[[language]]
name = "json"
# Pretier
# formatter = { command = 'prettier', args = ["--parser", "json"] }
# Deno
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "json" ] }

[[language]]
name = "css"
# Pretier
# formatter = { command = 'prettier', args = ["--parser", "css"] }
# Deno
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "css" ] }

# Copied from https://github.com/helix-editor/helix/blob/master/languages.toml#L117-L138
# [[foo]] notation adds to the foo table as a list item. So each entry for a language
# presumably overwrites the last with the same name when Helix comes to parse it. Thus, you need
# all the same keys for it to work.
[[grammar]]
name = "javascript"
source = { git = "https://github.com/tree-sitter/tree-sitter-javascript", rev = "f772967f7b7bc7c28f845be2420a38472b16a8ee" }

[[language]]
name = "jsx"
scope = "source.jsx"
injection-regex = "jsx"
language-id = "javascriptreact"
file-types = ["jsx"]
roots = []
comment-token = "//"
language-servers = ["typescript-language-server", "eslint"]
indent = { tab-width = 2, unit = "  " }
grammar = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[grammar]]
name = "typescript"
source = { git = "https://github.com/tree-sitter/tree-sitter-typescript", rev = "b1bf4825d9eaa0f3bdeb1e52f099533328acfbdf", subpath = "typescript" }

[[language]]
name = "typescript"
scope = "source.ts"
injection-regex = "(ts|typescript)"
file-types = ["ts", "mts", "cts"]
language-id = "typescript"
shebangs = []
roots = []
auto-format = true
grammar = "typescript"
# TSC
# language-servers = ["typescript-language-server", "eslint"]
# formatter = { command = 'prettier', args = ["--parser", "typescript"] }
# indent = { tab-width = 2, unit = "  " }
# Deno
language-servers = ["deno"]
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "ts" ] }

[[language]]
name = "tsx"
scope = "source.tsx"
injection-regex = "(tsx)" # |typescript
language-id = "typescriptreact"
file-types = ["tsx"]
roots = []
language-servers = ["typescript-language-server", "eslint"]
indent = { tab-width = 2, unit = "  " }
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
grammar = "typescript"
auto-format = true

[language-server.eslint]
args = ["--stdio"]
command = "vscode-eslint-language-server"

[language-server.eslint.config]
format = true
quiet = false
run = "onType"
validate = "on"
codeActionOnSave = { mode = "all" }

[language-server.typescript-language-server.config]
documentFormatting = false
hostInfo = "helix"

[language-server.deno]
command = "deno"
args = ["lsp"]
config = { deno = { enable = true } }
